version: '3.8'
services:
  web:
    build: .
    ports:
      - "5005:5005"
    environment:
      - FLASK_APP=app.py
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db/postgres
      - SQLALCHEMY_TRACK_MODIFICATIONS=False    
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
