apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: FLASK_APP
              value: app.py
            - name: SQLALCHEMY_DATABASE_URI
              value: postgresql://postgres:postgres@db/postgres
            - name: SQLALCHEMY_TRACK_MODIFICATIONS
              value: "False"
          image: web
          name: web
          ports:
            - containerPort: 5005
              protocol: TCP
      restartPolicy: Always
